name: xabe
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.3.5
  routemaster: ^1.0.1
  fpdart: ^1.1.1
  dotted_border: ^2.1.0
  file_picker: ^10.0.0
  any_link_preview: ^3.0.3
  uuid: ^4.5.1
  intl: ^0.20.1
  firebase_app_check: ^0.3.2+1
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  google_sign_in_web: ^0.12.4+4
  js: ^0.6.4
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  foundation: ^0.0.5
  typed_data: ^1.4.0
  image: ^4.5.3
  flutter_cache_manager: ^3.4.1
  collection: ^1.19.1
  get: ^4.7.2
  url_strategy: ^0.3.0
  google_nav_bar: ^5.0.7
  curved_navigation_bar: ^1.0.6
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.2.1
  google_mobile_ads: ^6.0.0

  path_provider: any
  flutter_native_splash: ^2.4.6
  crypto: ^3.0.6
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.2.5
  visibility_detector: ^0.4.0+2
  pay_with_paystack: ^1.0.14
  http: ^1.4.0
  cloud_functions: ^5.5.1
  url_launcher: ^6.3.1
  in_app_purchase: ^3.2.3
  googleapis: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.png"


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/logo.png
    - assets/images/premium_logo.png
    - assets/animations/loginanimation.json
    - assets/animations/voteanimation.json


  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
