// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6rI8AuBIyvtY8j5IAxOZYAWZZXLPAFX8',
    appId: '1:428700861857:android:3e940103f9bd6d9fdbf7e0',
    messagingSenderId: '428700861857',
    projectId: 'xabe-ai',
    storageBucket: 'xabe-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohLl56rLLw0dKQiqJo7O3HEIAnPhDVDc',
    appId: '1:428700861857:ios:f376203a49414013dbf7e0',
    messagingSenderId: '428700861857',
    projectId: 'xabe-ai',
    storageBucket: 'xabe-ai.firebasestorage.app',
    iosClientId:
        '428700861857-hu540ci7jn3lgsbsghc7fial07n2ffsu.apps.googleusercontent.com',
    iosBundleId: 'com.nubiarabo.rogueFashion',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALVaUXzWOn3fP2PjsxXXkdd2UC_Om4dGc',
    appId: '1:428700861857:web:996ae3b1b7050392dbf7e0',
    messagingSenderId: '428700861857',
    projectId: 'xabe-ai',
    authDomain: 'xabe-ai.firebaseapp.com',
    storageBucket: 'xabe-ai.firebasestorage.app',
    measurementId: 'G-Z1R8J6H3J2',
  );
}
